#!/bin/bash

CACHE_FILE="$HOME/.cache/rnm_history"

##
push_history(){
    local num_lines=0
    if [ -f "$CACHE_FILE" ]; then
        num_lines=$(wc -l < "$CACHE_FILE")
    fi
    echo "$1\n" >> "$CACHE_FILE"
###


hlpmsg(){
    echo "Usage: rnm [action]|[<path> <new_name>]
    path: (string) path to file o directory to rename
    new_name: (string) new name for file or directory

    actions:
        -r, --rollback manage in the history
    "

}

# HELP
if [[ -z "$1" || "$1" == "--help" || "$1" == "-h" ]]; then
    hlpmsg
    exit 0
fi

# Rollback
if [[ "$1" == "--rollback" || "$1" == "-r" ]]; then
    echo "No implemented yet"
    exit 0
fi

#

file_to_rename="$1"
rlpth=$(realpath $1)
bsdr=$(dirname $rlpth)


if [ ! -f "$file_to_rename" ]; then
    echo "No such file or directory '$file_to_rename '"
    exit 1
fi

########
mv "$rlpth" "$bsdr/$2"
########
echo "rename '$rlpth' -> '$bsdr/$2'"
push_history "$rlpth:$bsdr/$2"